[package]
name = "flashcards-services"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
flashcards-domain = { path = "../domain" }
flashcards-engines = { path = "../engines" }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
